/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_example_testjni_VideoCompress */

#ifndef _Included_com_example_testjni_VideoCompress
#define _Included_com_example_testjni_VideoCompress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testjni_VideoCompress
 * Method:    getSignature
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_testjni_VideoCompress_getSignature
  (JNIEnv *, jobject);

/*
 * Class:     com_example_testjni_VideoCompress
 * Method:    compressVideo
 * Signature: ([Ljava/lang/String;Lcom/example/testjni/VideoCompress/CompressCallback;)V
 */
JNIEXPORT void JNICALL Java_com_example_testjni_VideoCompress_compressVideo
  (JNIEnv *, jobject, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
