/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_example_testjni_VideoCompress_CompressCallback */

#ifndef _Included_com_example_testjni_VideoCompress_CompressCallback
#define _Included_com_example_testjni_VideoCompress_CompressCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
