server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能
      routes:
        - id: payment_routh #payment_route 路由ID，要求唯一
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          filters:
            - AddRequestParameter=X-Request-Id, 1024
          predicates:
            - Path=/payment/get/** #断言，路径匹配进行路由
            #After, Before, Between for time level
            - After=2020-02-21T15:51:37.485+8:00[Asia/Shanghai] # ZonedDateTime zbj = ZonedDateTime.now();  //默认时区
            #Cookie level
            - Cookie=username, zzyy
            #Header level
            - Header=X-Request-ID, \d+ #请求头要有X-Request-Id属性，并且值为整数的正则表达式
            - Host=**.atguigu.com
            - Method=GET
            - Query=username, \d+ #要有参数名username并且值要是整数

        - id: payment_routh2 #payment_route
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**

eureka:
  #instance:
  #appname: cloud-payment-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #心跳时间间隔
    lease-renewal-interval-in-seconds: 30
    #超时时间
    lease-expiration-duration-in-seconds: 90